apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerkodev2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockerkodev2
  template:
    metadata:
      labels:
        app: dockerkodev2
    spec:
      containers:
      - name: hello-python
        image: ghcr.io/lukassorensen/dockerkode:latest
        imagePullPolicy: Always

