apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerkode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockerkode
  template:
    metadata:
      labels:
        app: dockerkode
    spec:
      containers:
      - name: hello-python
        image: ghcr.io/lukassorensen/dockerkode:latest
        imagePullPolicy: Always

