name: Byg docker image

on:
  push:
    branches:
      -main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Byg Docker image
        run: docker build -t "DockerKode" ./Docker
      
      - name: Test image
        run: docker run "DockerKode"